# Generated by Django 5.0.2 on 2024-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=10000),
        ),
    ]
