# Generated by Django 5.0.2 on 2024-02-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0002_alter_news_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('photo', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
    ]
