# Generated by Django 5.0.2 on 2024-02-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0003_news_body_remove_news_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rank',
            field=models.CharField(max_length=8),
        ),
    ]
