# Generated by Django 5.0.2 on 2024-02-19 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0004_alter_news_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
