# Generated by Django 5.0.2 on 2024-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0005_news_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(),
        ),
    ]
