# Generated by Django 5.0.2 on 2024-02-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0006_alter_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_body',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_bodies', to='RAG.news'),
        ),
    ]
