# Generated by Django 5.0.2 on 2024-05-09 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0012_a_news_b_news_c_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_news',
            name='news_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='b_news',
            name='news_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='c_news',
            name='news_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
