# Generated by Django 5.0.2 on 2024-05-10 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0013_a_news_news_date_b_news_news_date_c_news_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('rank', models.IntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('news_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
