# Generated by Django 5.0.2 on 2024-05-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0014_general_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_news',
            name='press_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
