# Generated by Django 5.0.2 on 2024-05-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0015_general_news_press_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG.news')),
            ],
        ),
    ]
