# Generated by Django 5.0.2 on 2024-05-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0016_general_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_summary',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG.general_news'),
        ),
    ]
